# Extension: REST Client by Huachao Mao

@URL = http://localhost:3000
@JWT = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5MjQxN2E5YmFhNjFkNTZmNTNiYTc5MSIsImVtYWlsIjoiam9obkBnbWFpbC5jb20iLCJpYXQiOjE3NjM5NzMwNDIsImV4cCI6MTc2Mzk4MDI0Mn0.LRKwbjauJ6MRsCDLDNUaR_JMpFxRKrl05kk_yVJ60pY
@JWT_Sam = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5MjQxODBkYmFhNjFkNTZmNTNiYTc5NiIsImVtYWlsIjoic2FtQGdtYWlsLmNvbSIsImlhdCI6MTc2Mzk3MzE0MCwiZXhwIjoxNzYzOTgwMzQwfQ.5iFMJXC6atTH7BOAET48isoVeyWo6n-ttiXsvUkDyuw

POST {{URL}}/auth/register HTTP/1.1
Content-Type: application/json

{
	"userName": "john",
	"email": "john@gmail.com",
	"password": "password"
}

###
POST {{URL}}/auth/register HTTP/1.1
Content-Type: application/json

{
	"userName": "sam",
	"email": "sam@gmail.com",
	"password": "password"
}

###
POST {{URL}}/auth/login HTTP/1.1
Content-Type: application/json

{
	"email": "john@gmail.com",
	"password": "password"
}

### replace the token!
GET {{URL}}/auth/profile HTTP/1.1
Authorization: Bearer {{JWT}}
