# Extension: REST Client by Huachao Mao

@URL = http://localhost:3000
@JWT = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5MmFjOGI4OTNmNWE2MzMyOGI2ZmUwNCIsImlhdCI6MTc2NDQyNTk5NSwiZXhwIjoxNzY1MDMwNzk1fQ.aOvwpzCp48kSeYmZlioVFAw6xUHSt5m7iXOLz-TBO5k
@JWT_SUPERADMIN = 







### WARNING: OUTDATED. USE INSOMNIA. ###





### replace the token!
POST {{URL}}/auth/login HTTP/1.1
Content-Type: application/json

{
	"email": "john@gmail.com",
	"password": "password"
}

#> {%
#	client.global.set("JWT", response.body.token)
#%}
# TODO: create a .env file just for testing and
# set the JWT automatically 

### 
GET {{URL}}/auth/profile HTTP/1.1
Authorization: Bearer {{JWT}}


###
POST {{URL}}/auth/register HTTP/1.1
Content-Type: application/json

{
	"userName": "john",
	"email": "john@gmail.com",
	"password": "password"
}

###
POST {{URL}}/auth/login HTTP/1.1
Content-Type: application/json

{
	"email": "sam@gmail.com",
	"password": "password"
}

### 
GET {{URL}}/auth/profile HTTP/1.1
Authorization: Bearer {{{{JWT_SUPERADMIN}}}}

###
POST {{URL}}/auth/register HTTP/1.1
Content-Type: application/json

{
	"userName": "sam",
	"email": "sam@gmail.com",
	"password": "password"
}