@URL = http://localhost:3000
@JWT = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5Mjg2M2QzODY5NjgxMzQ0OTllNTVkMiIsImVtYWlsIjoiam9obkBnbWFpbC5jb20iLCJpYXQiOjE3NjQyNjAzMTMsImV4cCI6MTc2NDg2NTExM30.575w8IKKYUGgOQ-8NKCmfuJl0zReQqz3qXCaRUuWhUk
@USER_ID = 6926b4692c4aad55d363e9da
@LIST_ID = 692879f8145be6837de600d5

###
GET {{URL}}/shoppinglists/{{LIST_ID}} HTTP/1.1
Authorization: Bearer {{JWT}}

###
GET {{URL}}/users/{{USER_ID}}/shoppinglists?page=1&pageSize=10
Authorization: Bearer {{JWT}}

### debug / admin only
GET {{URL}}/shoppinglists/listAll

###
PUT {{URL}}/shoppinglists HTTP/1.1
Authorization: Bearer {{JWT}}
Content-Type: application/json

{
	"name": "Another shopping list"
}

###
PATCH {{URL}}/shoppinglists/{{LIST_ID}} HTTP/1.1
Authorization: Bearer {{JWT}}
Content-Type: application/json

{
	"name": "patched name",
	"memberList": ["eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5MjMxYmEzMjM1NDc2NGJmNDI1NGNmMyIsImVtYWlsIjoiam9obkBnbWFpbC5jb20iLCJpYXQiOjE3NjQwNjE4ODMsImV4cCI6MTc2NDY2NjY4M30.jCAXcZgMvBHbz-1gS0bj7yar2EBnEy8MhQUKbkw6pPM"],
	"itemList": [
		{
			"_id": "69287a02145be6837de600d9",
			"name": "MODIFIED",
			"ticked": true
		},
		{
			"_id": "69287a02145be6837de600da",
			"name": "UPDATED",
			"unit": "30",
			"ticked": true
		}
	]
}

###
PATCH {{URL}}/shoppinglists/{{LIST_ID}} HTTP/1.1
Authorization: Bearer {{JWT}}
Content-Type: application/json

{
	"itemList": [
		{
			"name": "milk",
			"quantity": 2,
			"unit": "l"
		}
	]
}

###
DELETE {{URL}}/shoppinglists/{{LIST_ID}} HTTP/1.1
Authorization: Bearer {{JWT}}
Content-Type: application/json

{
	"_id": "69287cb5ae90612f6ac72956"
}

###
