@URL = http://localhost:3000
@JWT = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5MjljNDk2MWU3ZTkzZGJjNDkxNjkwOCIsImVtYWlsIjoiam9obkBnbWFpbC5jb20iLCJpYXQiOjE3NjQzNDQ5ODQsImV4cCI6MTc2NDk0OTc4NH0.TxhL1naMWYgXDDcfx6XBGX-FAWLj1AWfGCImmku4swQ
@USER_ID = 692863d386968134499e55d2
@LIST_ID = 6929c52e1e7e93dbc491690c

###
GET {{URL}}/shoppinglists/{{LIST_ID}} HTTP/1.1
Authorization: Bearer {{JWT}}

###
GET {{URL}}/users/{{USER_ID}}/shoppinglists?page=1&pageSize=10
Authorization: Bearer {{JWT}}

### debug / admin only
GET {{URL}}/shoppinglists/listAll
Authorization: Bearer {{JWT}}

###
PUT {{URL}}/shoppinglists HTTP/1.1
Authorization: Bearer {{JWT}}
Content-Type: application/json

{
	"name": "Another shopping list"
}

###
PATCH {{URL}}/shoppinglists/{{LIST_ID}} HTTP/1.1
Authorization: Bearer {{JWT}}
Content-Type: application/json

{
	"name": "patched name",
	"memberList": ["eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5MjMxYmEzMjM1NDc2NGJmNDI1NGNmMyIsImVtYWlsIjoiam9obkBnbWFpbC5jb20iLCJpYXQiOjE3NjQwNjE4ODMsImV4cCI6MTc2NDY2NjY4M30.jCAXcZgMvBHbz-1gS0bj7yar2EBnEy8MhQUKbkw6pPM"],
	"itemList": [
		{
			"_id": "69288a08cf9c859afe2da015",
			"name": "d",
			"ticked": true
		},
		{
			"_id": "69287a02145be6837de600da",
			"name": "UPDATED",
			"unit": "30",
			"ticked": true
		}
	]
}

###
PATCH {{URL}}/shoppinglists/{{LIST_ID}} HTTP/1.1
Authorization: Bearer {{JWT}}
Content-Type: application/json

{
	"itemList": [
		{
			"name": "milk",
			"quantity": 2,
			"unit": "l"
		}
	]
}

###
DELETE {{URL}}/shoppinglists/{{LIST_ID}} HTTP/1.1
Authorization: Bearer {{JWT}}

###
